### PR TITLE
MySQL support and guard on number of schemas

### PR DESCRIPTION
**Pull request by manthey**
Don't list schemas if there are too many of them.

This should be made configurable.

Also, don't fail if we can't set the current session to read-only.

### CODE REVIEW

**Comment by manthey** [comment]
This branch now adds first-class MySQL support, including functions and regex searches.

I've changed the title to match.

**Comment by manthey** [comment]
This is ready for review.

**Comment by matthewma7** [comment]
@manthey, I did my best and took a look code and poke around in the test, everything looks good to me.

**Comment by manthey** [comment]
@matthewma7 Can you approve the PR, then?  Thanks.

**Comment by manthey** [comment]
Thank you.

**Pull request merged**
